//Mock data for recommended destination carousel
export const popularDestinationCarousel = [
  {
    id: 1,
    name: "New York",
    country: "United States",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9",
    description: "Experience the vibrant culture and iconic landmarks of the city that never sleeps.",
    price: 299,
  },
  {
    id: 2,
    name: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    description: "Discover the romance and charm of the City of Light with its world-class cuisine and art.",
    price: 449,
  },
  {
    id: 3,
    name: "Tokyo",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26",
    description: "Immerse yourself in the perfect blend of traditional culture and futuristic technology.",
    price: 799,
  },
  {
    id: 4,
    name: "Rome",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    description: "Walk through history in the Eternal City with its ancient ruins and Renaissance masterpieces.",
    price: 399,
  },
  {
    id: 5,
    name: "Sydney",
    country: "Australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
    description: "Enjoy the stunning harbor views and laid-back lifestyle of Australia's iconic city.",
    price: 899,
  },
  {
    id: 6,
    name: "Dubai",
    country: "UAE",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    description: "Experience luxury and innovation in this ultramodern desert metropolis.",
    price: 599,
  },
];
